name: jura_app
description: Jura Lawyer Management - Multiplatform
publish_to: "none"
version: 0.0.1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^ 7.1.1
  stream_transform: ^2.1.0
  http: ^1.1.0
  provider: ^6.0.0
  web_socket_channel: ^2.1.0
  url_launcher: ^6.1.7
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - flutter_app/assets/splash-screen.png
    - flutter_app/assets/splash-screen-black-BG.png
    - flutter_app/assets/login-screen.png
